---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - krox.io
  resources:
  - kroxdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krox.io
  resources:
  - kroxdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - krox.io
  resources:
  - kroxdeployments/status
  verbs:
  - get
  - patch
  - update
