apiVersion: krox.io/v1alpha1
kind: KroxDeployment
metadata:
  name: webapp-prod
  namespace: apps
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: blueprints
    namespace: flux-system
  path: ./rgds/webapp.yaml
  values:
    name: web
    replicas: 3
    image: nginx:1.27
  prune: true
